### ISSUE TITLE
null description

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-services#13]
"null" shows up in the italic description text for Mountain Terrace, for example. Not sure if it's actually a data problem, but in any case it should probably return or display an empty string or something for null data.

**Comment by awoodruff** [comment]
(not sure if this is best solved on the front end or back end)

**Comment by davidheyman** [comment]
There's no reason the description field needs to be a separate call. This can be integrated into the template and take advantage of the code that already checks for NULL values.
