### ISSUE TITLE
iPad: things get wonky when rotating

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-services#17]
This is tricky to describe, but...
When the tablet is rotated from landscape to portrait, window sizing can get messed up. I can drag the header area to scroll the page left and right. Sometimes the side panel (if it's open) scrolls along with it, and sometimes things kind of slide underneath or on top of it. I don't know if this is 100% true but it seems to happen mainly if I rotate when the search box has focus and the on-screen keyboard is visible. Similarly, sometimes when rotating from portrait to landscape, there is some vertical scroll room.

**Comment by kingfisher13** [comment]
I can only get it to do wonky stuff if both the keyboard and the sidebar are open and I go from landscape to portrait. When that sequence happens, the sidebar ends up short. Even then, as soon as the keyboard disappears, the sidebar returns to full length.

**Comment by kingfisher13** [comment]
I bet the fix to #19 will fix this.
