### ISSUE TITLE
Map extents with side panel open

### ISSUE THREAD

**Issue by awoodruff** [axismaps/bcworkshop-services#19]
I first noticed this on the iPad, but it's a general issue with narrow-ish browser windows. When the side panel is visible in a narrow window at zoom level 11 or so, it covers enough of the map that the maximum bounds won't allow you to pan to see the whole thing. For example in the screenshot below I can't pan left to see the rest of Dallas.

![screen shot 2015-03-18 at 2 03 16 pm](https://cloud.githubusercontent.com/assets/3533462/6715871/eee2661a-cd77-11e4-8430-d5c4865833de.png)

The map div itself could be pushed right and narrowed so that it fills the visible space instead of going underneath the aside. (It can simultaneously be panned back a bit so that it doesn't appear to jump. I just did such a thing on another map yesterday and would be happy to do it here too if desired.)

**Comment by kingfisher13** [comment]
@awoodruff If you wouldn't mind doing this since you did it so recently, that would be great.
